ci: add branch preparation CI changes
Signed-off-by: Abhinandan Purkait <purkaitabhinandan@gmail.com>

diff --git a/.github/workflows/build_and_push.yml b/.github/workflows/build_and_push.yml
--- a/.github/workflows/build_and_push.yml
+++ b/.github/workflows/build_and_push.yml
@@ -52,73 +52,74 @@ jobs:
           name: coverage-$(date +%s)
           flags: unittests
 
-  bdd-tests:
-    runs-on: ubuntu-latest
-    needs: ["unit-tests"]
-    strategy:
-      fail-fast: true
-      matrix:
-        kubernetes: [v1.27.3]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # bdd-tests:
+  #   runs-on: ubuntu-latest
+  #   needs: ["unit-tests"]
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       kubernetes: [v1.27.3]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Set up Go 1.19
-        uses: actions/setup-go@v4
-        with:
-          go-version: 1.19.9
-          cache: false
+  #     - name: Set up Go 1.19
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: 1.19.9
+  #         cache: false
 
-      - name: Build images locally
-        run: make zfs-driver-image || exit 1;
+  #     - name: Build images locally
+  #       run: make zfs-driver-image || exit 1;
 
-      - name: Setup zfs pools
-        run: |
-          sudo apt-get install zfsutils-linux -y
-          truncate -s 100G /tmp/disk.img
-          sudo zpool create zfspv-pool $(sudo losetup -f /tmp/disk.img --show)
+  #     - name: Setup zfs pools
+  #       run: |
+  #         sudo apt-get install zfsutils-linux -y
+  #         truncate -s 100G /tmp/disk.img
+  #         sudo zpool create zfspv-pool $(sudo losetup -f /tmp/disk.img --show)
 
-      - name: Setup Minikube-Kubernetes
-        uses: medyagh/setup-minikube@latest
-        with:
-          cache: false
-          minikube-version: 1.31.1
-          driver: none
-          kubernetes-version: ${{ matrix.kubernetes }}
-          cni: calico
-          start-args: "--install-addons=false"
+  #     - name: Setup Minikube-Kubernetes
+  #       uses: medyagh/setup-minikube@latest
+  #       with:
+  #         cache: false
+  #         minikube-version: 1.31.1
+  #         driver: none
+  #         kubernetes-version: ${{ matrix.kubernetes }}
+  #         cni: calico
+  #         start-args: "--install-addons=false"
 
-      - name: Setting environment variables
-        run: |
-          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
-          echo "OPENEBS_NAMESPACE=openebs" >> $GITHUB_ENV
+  #     - name: Setting environment variables
+  #       run: |
+  #         echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
+  #         echo "OPENEBS_NAMESPACE=openebs" >> $GITHUB_ENV
 
-      - name: bootstrap
-        run: make bootstrap
+  #     - name: bootstrap
+  #       run: make bootstrap
 
-      - name: Running tests
-        run: |
-          make ci
-          make sanity
+  #     - name: Running tests
+  #       run: |
+  #         make ci
+  #         make sanity
 
-      - name: Upload CI Test Coverage Report
-        uses: codecov/codecov-action@v4
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          file: ./tests/bdd_coverage.txt
-          name: coverage-bdd_coverage-$(date +%s)
-          flags: bddtests
+  #     - name: Upload CI Test Coverage Report
+  #       uses: codecov/codecov-action@v4
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         file: ./tests/bdd_coverage.txt
+  #         name: coverage-bdd_coverage-$(date +%s)
+  #         flags: bddtests
 
   csi-driver:
     runs-on: ubuntu-latest
-    needs: ["lint", "bdd-tests"]
+    #needs: ["lint", "bdd-tests"]
+    needs: ["lint"]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Set Image Org
         run: |
-          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG}}
+          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=abhinandan15 || IMAGE_ORG=${{ secrets.IMAGE_ORG}}
           echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV
 
       - name: Set IMAGE_TAG and BRANCH
@@ -137,10 +138,10 @@ jobs:
         uses: docker/metadata-action@v4
         with:
           # add each registry to which the image needs to be pushed here
+          # quay.io/${{ env.IMAGE_ORG }}/zfs-driver
+          # ghcr.io/${{ env.IMAGE_ORG }}/zfs-driver
           images: |
             ${{ env.IMAGE_ORG }}/zfs-driver
-            quay.io/${{ env.IMAGE_ORG }}/zfs-driver
-            ghcr.io/${{ env.IMAGE_ORG }}/zfs-driver
           tags: |
             type=raw,value=latest,enable=false
             type=raw,value=${{ env.IMAGE_TAG }}
@@ -167,19 +168,19 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Login to Quay
-        uses: docker/login-action@v3
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
+      # - name: Login to Quay
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: quay.io
+      #     username: ${{ secrets.QUAY_USERNAME }}
+      #     password: ${{ secrets.QUAY_TOKEN }}
 
-      - name: Login to GHCR
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Login to GHCR
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build & Push Image
         uses: docker/build-push-action@v5
